### ISSUE TITLE
Vertical support.

### ISSUE THREAD

**Issue by darkkillen** [HirayClay/StackLayoutManager#2]
I'm very interested in StackLayoutManager but I want to use in vertical recyclerView.

Thank you for your support.

**Comment by HirayClay** [comment]
Actually vertical StackLayoutManager is quite smiliar with horizontal ,i have written the vertical support code,but just write for fun and some bugs -_-||. From the very beginning ,this project is intended to implement ![android-pilelayout](https://github.com/xmuSistone/AndroidPileLayout) with LayoutManager , not considering vertical support.
If you really need verticall support,i will try .
