### ISSUE TITLE
Cards with Match_Parent width and height

### ISSUE THREAD

**Issue by jyoti-AndroidDeveloper** [HirayClay/StackLayoutManager#5]
How can I change it to display full size image to fill the screen?

**Comment by HirayClay** [comment]
Why you need StackLayoutManager to display image filling the screen,man, i don't get it at all. Giving the same size to each item is the precondition of StackLayoutManager if you need the 'stack'  effcts

**Comment by jyoti-AndroidDeveloper** [comment]
I am trying to display cards in recyclerview (like vertical viewpager with stack transformation). I am doing this because viewpager scrolls too slow and many issues with ontouch() event. I just want the animation( scale, alpha) when scrolling

**Comment by HirayClay** [comment]
ok, i get it .like this?--->
![match_parent](https://user-images.githubusercontent.com/12825256/39617249-896bc294-4fb1-11e8-8ef5-8454da2a0400.gif)
you just set match_parent to your item is ok .Maybe my project example  confused you where i set  fixed size .

**Comment by jyoti-AndroidDeveloper** [comment]
@HirayClay Thanks for your replay. I just changed some code from your sample. it works fine

**Comment by jyoti-AndroidDeveloper** [comment]
@HirayClay Thanks for your replay. I just changed some code from your sample. it works fine

**Comment by jyoti-AndroidDeveloper** [comment]
`scrollToPosition() ` is not working If I used this LayoutManager.

**Comment by HirayClay** [comment]
now it works
